version: '3.1'

services:
  mysql:
    image: mysql
    volumes:
      - mysqldb:/data/db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
  app:
    image: app:latest
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 8080:8080
    depends_on:
      - mysql

volumes:
  mysqldb: